
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Home
 */
public class SETUP extends javax.swing.JFrame {

    /**
     * Creates new form SETUP
     */
    public SETUP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("SETUP THE APPLICATION");

        jButton1.setText("SETUP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(92, 92, 92)
                .addComponent(jButton1)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            Class.forName("java.sql.DriverManager");
Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Suvansh51","root","abc123");
Statement stmt = (Statement) con.createStatement();
String q="Create Database SETI;";
stmt.executeUpdate(q);
String q1="Create Database Happy;";
stmt.executeUpdate(q1);

{Connection co = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SETI","root","abc123");
Statement stm = (Statement) co.createStatement();
String qu="Create Table SETUP(YES varchar(10));";
stm.executeUpdate(qu);
String que="INSERT INTO SETUP VALUES('yes') ;";
stm.executeUpdate(que);}

{Connection co = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Happy","root","abc123");
Statement stm1 = (Statement) co.createStatement();
String qu1="Create Table Cus(ID INT,NAME VARCHAR(50),USERNAME VARCHAR(50),PASSWORD VARCHAR(50),ADDRESS VARCHAR(100),DOB DATE,MOBILE INT(10)"
        + ",EMAIL VARCHAR(75),RIDES INT,TOTALFARE INT,QUERY VARCHAR(255),M VARCHAR(255));";
stm1.executeUpdate(qu1);
}

{Connection co = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Happy","root","abc123");
Statement stm = (Statement) co.createStatement();
String qu="Create Table Dri(ID INT,NAME VARCHAR(50),USERNAME VARCHAR(50),PASSWORD VARCHAR(50),ADDRESS VARCHAR(100),DOB DATE,MOBILE INT(10),"
        + "EMAIL VARCHAR(75),RIDES INT,TOTALFARE INT,QUERY VARCHAR(255),TYPE VARCHAR(10),MODEL VARCHAR(30),NUMBER INT(15),COMMISIONS INT(10),FINES INT(10),M VARCHAR(255));";
stm.executeUpdate(qu);
}

{Connection co = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Happy","root","abc123");
Statement stm = (Statement) co.createStatement();
String qu="Create Table Admin(ID INT,PASSWORD VARCHAR(50));";
stm.executeUpdate(qu);
String qt="insert into Admin values(363,'htgc');";
stm.executeUpdate(qt);
}



        }
        catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}
        JOptionPane.showMessageDialog(this,"The Programme is set up and ready to use.");
        new PAGE().setVisible(true);
this.setVisible(false);

  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SETUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SETUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SETUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SETUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SETUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
